all:
  vars:
    ansible_network_os: ios
    ansible_ssh_user: ec2-user
    #ansible_ssh_private_key_file: files/ssh_private_key.pem

  children:
    site1:
      children:
        tag_location_site1:

    site2:
      children:
        tag_location_site2:
